
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SandyDheringe/brs-config-service-properties.git
        default-label: master
server:
  port: 8071